events {
    worker_connections 1024;
}

http {
    client_max_body_size 20M;
    server {
        listen 80;
        server_name isuncoin.localhost;

        location / {
            proxy_pass http://isuncoin:8545;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name storage.localhost;

        location / {
            proxy_pass http://storage:10014;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 80;
        server_name ollama.localhost;

        location / {
            proxy_pass http://ollama:11434;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Default fallback
    server {
        listen 80 default_server;
        server_name _;
        return 404;
    }
}
